name: Run Tests

on:
  push:
    paths-ignore:
      - src/main/resources/**
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'
          cache: 'maven'
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: v1/${{ runner.os }}/java-17/${{ hashFiles('**/package-lock.json') }}
          restore-keys: v1/${{ runner.os }}/java-17/
      - run: make install
      - run: make test
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}